apiVersion: myexample.com/v1
kind: DataContract
metadata:
  name: example2
spec:
  name: Example Contract 2
  version: '1.2.0'
  statusIcon: false
  status: active
  description: This is an example data contract on gitHub
